spring:
  application:
    name: store
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 #2H
    refreshTokenExpiration: 604800 #7d
  profiles:
    active: ${SPRING_PROFILES_ACTIVE}
  stripe:
    secretKey: ${STRIPE_SECRET_KEY}
    webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}